config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :materials
  end
  # namespace :project do
  #   resources :materials
  # end
  resources :projects do
    resources :labours
  end
  # namespace :project do
  #   resources :labours
  # end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/labour.rb
class Labour < ApplicationRecord
  belongs_to :project
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :project

  validates :name, inclusion: {in: ['سیمنٹ', 'سٹیل','بجری', 'ریت', 'اینٹ','دیگر مواد']}

  MATERIAL_OPTIONS = [
  ['سیمنٹ', 'سیمنٹ'],
  ['بجری', 'بجری'],
  ['ریت', 'ریت'],
  ['سٹیل', 'سٹیل'],
  ['اینٹ', 'اینٹ'],
  ['دیگر مواد','دیگر مواد'],
  ]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :materials, dependent: :delete_all
  has_many :labours, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/labours_controller.rb
class LaboursController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_labour, only: [:show, :edit, :update, :destroy]

  # GET projects/1/labours
  def index
    @labours = @project.labours
  end

  # GET projects/1/labours/1
  def show
  end

  # GET projects/1/labours/new
  def new
    @labour = @project.labours.build
  end

  # GET projects/1/labours/1/edit
  def edit
  end

  # POST projects/1/labours
  def create
    @labour = @project.labours.build(labour_params)

    @labour.project.total_expense = @labour.project.total_expense + @labour.weekly_expense
    if @labour.save
      @labour.project.save
      redirect_to(@labour.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/labours/1
  def update
    @labour.project.total_expense = @labour.project.total_expense - @labour.weekly_expense

    if @labour.update(labour_params)
      @labour.project.total_expense = @labour.project.total_expense + @labour.weekly_expense
      @labour.project.save
      redirect_to(@labour.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/labours/1
  def destroy

    @labour.project.total_expense = @labour.project.total_expense - @labour.weekly_expense
    @labour.project.save
    @labour.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_labour
      @labour = @project.labours.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def labour_params
      params.require(:labour).permit(:weekend_date, :weekly_expense, :project_id)
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET projects/1/materials
  def index
    sessionStorage[:sort] = params[:sort]
    @materials = @project.materials.order(params[:sort])
  end

  # GET projects/1/materials/1
  def show
  end

  # GET projects/1/materials/new
  def new
    @material = @project.materials.build
  end

  # GET projects/1/materials/1/edit
  def edit
  end

  # POST projects/1/materials
  def create
    @material = @project.materials.build(material_params)

    @material.total_cost = @material.quantity * @material.per_unit_price
    @material.project.total_expense = @material.project.total_expense + @material.total_cost
    if @material.save
      @material.project.save
      redirect_to(@material.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/materials/1
  def update
    @material.project.total_expense = @material.project.total_expense - @material.total_cost

    if @material.update(material_params)
      @material.project.total_expense = @material.project.total_expense + @material.total_cost
      @material.project.save
      redirect_to(@material.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/materials/1
  def destroy
    @material.project.total_expense = @material.project.total_expense - @material.total_cost
    @material.project.save
    @material.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_material
      @material = @project.materials.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def material_params
      params.require(:material).permit(:name, :purchase_date, :per_unit_price, :quantity, :total_cost, :category, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @sort_material =  params[:sort_material] ? params[:sort_material] : "id"
    @sort_material_order =  params[:sort_material_order] ? params[:sort_material_order] : "DESC"

    @sort_labour =  params[:sort_labour] ? params[:sort_labour] : "id"
    @sort_labour_order =  params[:sort_labour_order] ? params[:sort_labour_order] : "DESC"
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.total_expense = 0
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :address, :started_on, :completed_on, :finished, :owner_name, :size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labours_helper.rb
module LaboursHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/labours/_form.html.haml
= form_for [@labour.project, @labour] do |f|
  -if @labour.errors.any?
    #error_explanation
      %h2= "#{pluralize(@labour.errors.count, "error")} prohibited this labour from being saved:"
      %ul
        - @labour.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :weekend_date, "ہفتہ وار تاریخ"
    = f.date_select :weekend_date
  .form-group
    = f.label :weekly_expense, "ہفتاور خرچہ"
    = f.number_field :weekly_expense, required: true, class: "form-control"

  .actions
    = f.submit class: "btn btn-success" do
      %i.fa.fa-save

app/views/labours/edit.html.haml
.card
  .card-title
    %h2.text-primary.ml-4.mt-2 Editing labour
  .card-body
    = render 'form'

  = link_to [@labour.project, @labour], class: "btn btn-info" do
    %i.fa.fa-eye
  = link_to project_path(@labour.project), class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/labours/index.html.haml
%h1 Listing labours

%table
  %tr
    %th Weekend date
    %th Weekly expense
    %th Project
    %th
    %th
    %th

  - @labours.each do |labour|
    %tr
      %td= labour.weekend_date
      %td= labour.weekly_expense
      -# %td= labour.project
      %td= link_to 'Show', [labour.project, labour]
      %td= link_to 'Edit', edit_project_labour_path(labour.project, labour)
      %td= link_to 'Destroy', [labour.project, labour], data: { confirm: 'Are you sure?' }, method: :delete

%br

= link_to 'New Labour', new_project_labour_path(params[:project_id])

app/views/labours/new.html.haml
.card
  .card-title
    %h2.text-primary.ml-4.mt-2 New labour
  .card-body
    = render 'form'

  = link_to project_path(@labour.project), class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/labours/show.html.haml
.card
  .card-body
    %p
      %b ہفتہ وار تاریخ:
      = @labour.weekend_date
    %p
      %b ہفتاور خرچہ:
      = @labour.weekly_expense

  = link_to edit_project_labour_path(@labour.project, @labour), class: "btn btn-warning" do
    %i.fa.fa-edit

  = link_to project_path(@labour.project), class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ArifEngineeringConstructionManagement
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %link{rel: "stylesheet", href: "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css", integrity: "sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l", crossorigin: "anonymous"}
    %script{src: "https://use.fontawesome.com/045009029f.js"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.pt-5
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/materials/_form.html.haml
= form_for [@material.project, @material] do |f|
  -if @material.errors.any?
    #error_explanation
      %h2= "#{pluralize(@material.errors.count, "error")} prohibited this material from being saved:"
      %ul
        - @material.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, "نام"
    = f.select :name, Material::MATERIAL_OPTIONS, required: true, class: "form-control"
  .form-group
    = f.label :purchase_date, "خریداری کی تاریخ"
    = f.date_select :purchase_date
  .form-group
    = f.label :per_unit_price, "فی آئٹم لاگت"
    = f.text_field :per_unit_price, required: true, class: "form-control"
  .form-group
    = f.label :quantity, "مقدار"
    = f.number_field :quantity, required: true, class: "form-control"
  .form-group
    = f.label :category, "شے کا نام"
    = f.text_field :category

  .actions
    = f.submit class: "btn btn-success" do
      %i.fa.fa-save

app/views/materials/edit.html.haml
.card
  .card-title
    %h2.text-primary.ml-4.mt-2 Editing material
  .card-body
    = render 'form'

  = link_to [@material.project, @material], class: "btn btn-info" do
    %i.fa.fa-eye
  = link_to project_path(@material.project), class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/materials/index.html.haml
%h1 Listing materials

%table
  %tr
    %th Name
    %th Purchase date
    %th Per unit price
    %th Quantity
    %th Total cost
    %th Category
    -# %th Project
    %th
    %th
    %th

  - @materials.each do |material|
    %tr
      %td= material.name
      %td= material.purchase_date
      %td= material.per_unit_price
      %td= material.quantity
      %td= material.quantity * material.per_unit_price
      %td= material.category
      -# %td= material.project
      %td= link_to 'Show', [material.project, material]
      %td= link_to 'Edit', edit_project_material_path(material.project, material)
      %td= link_to 'Destroy', [material.project, material], data: { confirm: 'Are you sure?' }, method: :delete

%br

= link_to 'New Material', new_project_material_path(params[:project_id])

app/views/materials/new.html.haml
.card
  .card-title
    %h2.text-primary.ml-4.mt-2 New material
  .card-body
    = render 'form'

  = link_to project_path(@material.project), class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/materials/show.html.haml
.card
  .card-body
    %p
      %b نام:
      = @material.name
    %p
      %b خریداری کی تاریخ:
      = @material.purchase_date
    %p
      %b فی آئٹم لاگت:
      = @material.per_unit_price
    %p
      %b مقدار:
      = @material.quantity
    %p
      %b لاگت:
      = @material.quantity * @material.per_unit_price
    %p
      %b شے کا نام:
      = @material.category

  = link_to edit_project_material_path(@material.project, @material), class: "btn btn-warning" do
    %i.fa.fa-edit

  = link_to  project_path(@material.project), class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name, "نام"
    = f.text_field :name, required: true, class: "form-control"
  .form-group
    = f.label :address, "ایڈریس"
    = f.text_field :address, required: true, class: "form-control"
  .form-group
    = f.label :started_on, "تاریخ شروعات"
    = f.date_select :started_on, {order: [ :day, :month, :year], end_year: Date.today.year}, {required: true}
  -# .form-group
  -#   = f.label :completed_on
  -#   = f.date_select :completed_on, {order: [ :day, :month, :year], end_year: Date.today.year - 10}, {required: true}
  .form-group
    = f.label :finished, "ختم"
    = f.check_box :finished, class: "form-check-label"
  .form-group
    = f.label :owner_name, "کلائنٹ کا نام"
    = f.text_field :owner_name, class: "form-control"
  .form-group
    = f.label :size, "رقبہ"
    = f.text_field :size, class: "form-control"
  .actions
    = f.submit class: "btn btn-success" do
      %i.fa.fa-Save

app/views/projects/_labour_index.html.haml
.col-sm
  %h4.font-weight-bold لیبر
  .btn.btn-link.d-inline
    = link_to :sort_labour_order => @sort_labour_order == "ASC" ? "DESC" : "ASC"  do
      -if @sort_labour_order == "ASC"
        %i.fa.fa-sort-up
      -else
        %i.fa.fa-sort-down

  %table.table.border
    %tr
      %th
        = link_to "تاریخ" , :sort_labour => "id"
      %th
        = link_to "خرچہ" , :sort_labour => "weekly_expense"
      %th

    - @project.labours.order("#{@sort_labour} #{@sort_labour_order}").each do |labour|
      %tr
        %td= labour.weekend_date
        %td= labour.weekly_expense
        %td
          = link_to [labour.project, labour], class: "btn btn-info mr-2" do
            %i.fa.fa-eye
          = link_to edit_project_labour_path(labour.project, labour), class: "btn btn-warning mr-2" do
            %i.fa.fa-edit
          = link_to [labour.project, labour], data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger" do
            %i.fa.fa-trash
  %h4 کل لیبر خرچہ: -/#{@project.labours.sum(:weekly_expense)}
  %br

  = link_to  new_project_labour_path(@project), class: "btn btn-primary" do
    %i.fa.fa-plus

app/views/projects/_material_index.html.haml
.col-sm
  %h4.font-weight-bold مٹیریل
  .btn.btn-link.d-inline
    = link_to :sort_material => "id" do
      %i.fa.fa-history
  .btn.btn-link.d-inline
    = link_to :sort_material_order => @sort_material_order == "ASC" ? "DESC" : "ASC" do
      -if @sort_material_order == "ASC"
        %i.fa.fa-sort-up
      -else
        %i.fa.fa-sort-down

  %form.d-inline{:action => '', :method => 'get'}
    = select_tag :filter_name, options_for_select(Material::MATERIAL_OPTIONS, params[:filter_name]), onchange: "this.form.submit();"
  .btn.btn-link.d-inline
    = link_to "سارے دکھاو" , :filter_clear => ""
  %table.table.border
    %tr
      %th= link_to "نام" , :sort_material => "name"
      %th= link_to "مقدار" , :sort_material => "quantity"
      %th= link_to "کل لاگت" , :sort_material => "total_cost"
      %th

    - if params[:filter_name]
      - @project.materials.where(name: params[:filter_name]).order("#{@sort_material} #{@sort_material_order}").each  do |material|
        %tr
          %td
            = material.name
          %td
            #{ material.per_unit_price} x #{ material.quantity}
          %td
            #{material.total_cost}/-
          %td
            = link_to [material.project, material], class: "btn btn-info mr-2" do
              %i.fa.fa-eye
            = link_to edit_project_material_path(material.project, material), class: "btn btn-warning mr-2" do
              %i.fa.fa-edit
            = link_to [material.project, material], data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger" do
              %i.fa.fa-trash
    - else
      - @project.materials.order("#{@sort_material} #{@sort_material_order}").each  do |material|
        %tr
          %td
            = material.name
          %td
            #{ material.per_unit_price} x #{ material.quantity}
          %td
            #{material.total_cost}/-
          %td
            = link_to [material.project, material], class: "btn btn-info mr-2" do
              %i.fa.fa-eye
            = link_to edit_project_material_path(material.project, material), class: "btn btn-warning mr-2" do
              %i.fa.fa-edit
            = link_to [material.project, material], data: { confirm: 'ڈیلیٹ کردیں ?' }, method: :delete, class: "btn btn-danger" do
              %i.fa.fa-trash

  - if params[:filter_name]
    %h4 کل #{params[:filter_name]} خرچہ: -/#{@project.materials.where(name: params[:filter_name]).sum(:total_cost)}
  - else
    %h4 کل مٹیریل خرچہ: -/#{@project.materials.sum(:total_cost)}
  %br
  = link_to new_project_material_path(@project), class: "btn btn-primary" do
    %i.fa.fa-plus

app/views/projects/edit.html.haml
.card
  .card-title
    %h2.text-primary.ml-4.mt-2 Editing project
  .card-body
    = render 'form'

  = link_to @project, class: "btn btn-info" do
    %i.fa.fa-eye
  = link_to @project, class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/projects/index.html.haml
.card.mb-4
  .card-body
    %h2.card-title.d-flex.justify-content-between.mb-4
      %span projects
      = link_to new_project_path, class: "btn btn-primary" do
        %i.fa.fa-plus

    جاری سائٹ:
    - @projects.each do |project|
      -if !project.finished
        =link_to project do
          .card
            .card-body
              %h4.card-title
                = project.name
              %p.d-inline
                = project.address
              %footer.blockquote-footer
                ( #{project.size} )

.card
  .card-body
    ختم سائٹ:
    - @projects.each do |project|
      -if project.finished
        =link_to project do
          .card
            .card-body
              %h4.card-title
                = project.name
              %p
                = project.address

app/views/projects/new.html.haml
.card
  .card-title
    %h2.text-primary.ml-4.mt-2 New project
  .card-body
    = render 'form'

  = link_to projects_path, class: "btn btn-primary" do
    %i.fa.fa-arrow-left

app/views/projects/show.html.haml
.mb-4
  = link_to  projects_path, class: "btn btn-primary" do
    %i.fa.fa-arrow-left
.card
  .card-body
    %h2.card-title.d-flex.justify-content-between.mb-4
      %span
        =@project.name
      %div
        = link_to edit_project_path(@project), class: "btn btn-warning mr-2" do
          %i.fa.fa-edit
        -# = link_to @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do
        -#   %i.fa.fa-trash
    .text-right
      %p
        %b Address :
        = @project.address
      %p
        %b تاریخ شروعات:
        = @project.started_on
      %p
        %b کلائنٹ کا نام:
        = @project.owner_name
      %h4
        %b مکمل خرچہ: -/
        #{@project.total_expense}
      %p
        %b size:
        = @project.size
    %hr/
    .container
      .row
        = render 'material_index'
        = render 'labour_index'